version: '3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    restart: always
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/playground-realm.json
    volumes:
      - ./playground-realm.json:/tmp/playground-realm.json
      - ./src/main/resources/themes/recaptcha:/opt/keycloak/themes/recaptcha
      - ./target/recaptcha-login.jar:/opt/keycloak/providers/recaptcha-login.jar
    ports:
      - 8080:8080